server:
  port: 10010 #服务端口
spring:
  application:
    name: api-gateway #指定服务名

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://192.168.79.118:10086/eureka, http://192.168.79.119:10087/eureka

zuul:
  prefix: /api
  routes:
    user-service:
        path: /user-service/**    #这里指的是映射路径  也就是rest风格的请求
        serviceId: user-service
#上面的等价于
#    user-service: /user-service/**



#zuul:
#  routes:
#    user-service: # 这里是路由id，随意写
#      path: /user-service/** # 这里是映射路径
#      url: http://127.0.0.1:8083 # 映射路径对应的实际url地址